name: Build

on:
  workflow_run:
    workflows:
      - 'Test'
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Name'
        run: echo "Running Build"
