name: Deploy React Application to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install nx command
        run: npm install -g nx
        
      - name: Install Dependencies
        run: yarn install

      - name: Fix nx?
        run: nx migrate 15.6.2

      - name: Install again
        run: yarn install
      
      - name: Build Project
        run: npx nx run react-trrack-example:build --prod --skip-nx-cache
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
