name: Deploy React Application to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install yarn
        run: npm install -g yarn
        
      - name: Install Dependencies
        run: yarn install

      - name: Fix nx?
        run: nx migrate 15.6.2

      - name: Install again
        run: yarn install
      
      - name: Build Project
        run: npx nx run react-trrack-example:build --prod
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/react-trrack-example
