name: Deploy React Application to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Set this to the node version you use locally
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npx nx run react-trrack-example:build --prod
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/react-trrack-example  # Update the path to where Nx outputs the build files
